import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
const styles = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");
const gamePage = readFileSync(new URL("../app/games/[slug]/page.tsx", import.meta.url), "utf8");
const browser = readFileSync(new URL("../app/catalog-browser.tsx", import.meta.url), "utf8");
const boxViewer = readFileSync(new URL("../app/game-box-viewer.tsx", import.meta.url), "utf8");
const cards = readFileSync(new URL("../app/catalog-cards.tsx", import.meta.url), "utf8");
const packageThumbnail = readFileSync(new URL("../app/package-thumbnail.tsx", import.meta.url), "utf8");
const taxonomyHub = readFileSync(new URL("../app/taxonomy-hub.tsx", import.meta.url), "utf8");
const catalogIndex = readFileSync(new URL("../app/catalog/page.tsx", import.meta.url), "utf8");
const staticExportValidator = readFileSync(new URL("../scripts/validate-static-export.mjs", import.meta.url), "utf8");

test("home shell exposes a keyboard bypass and stable main landmark", () => {
  assert.match(page, /className="skip-link" href="#main-content"/);
  assert.match(page, /<main id="main-content">/);
  assert.match(page, /<SiteHeader active="browse" \/>/);
  assert.match(page, /<SiteFooter \/>/);
});

test("home shell exposes accessible catalog search and filters", () => {
  assert.match(page, /CatalogBrowser/);
  assert.match(page, /getCatalogSearchRecords/);
  assert.doesNotMatch(page, /Catalog search is coming soon/);
  assert.doesNotMatch(page, /Catalog coming soon/);
  assert.doesNotMatch(page, /80\+/);
  assert.match(page, /browse every game in the no-JavaScript index/);
  assert.match(browser, /onSubmit=\{\(event\) => event\.preventDefault\(\)\}/);
  assert.match(browser, /addEventListener\("popstate"/);
  assert.doesNotMatch(browser, /Update results/);
  assert.match(browser, /browser-panel-count/);
  assert.match(browser, /htmlFor="catalog-sort"/);
  assert.match(browser, /browser-field browser-facet-field/);
  assert.match(browser, /More filters/);
  assert.doesNotMatch(browser, /activeSortLabel/);
  assert.match(browser, /Card layout/);
  assert.match(browser, /Single-column layout on smaller screens\./);
  assert.match(browser, /Automatic responsive card layout/);
  assert.match(browser, /Choose card images/);
  assert.match(browser, /showImages=\{state\.images !== "hide"\}/);
  assert.match(browser, /name="card-images" value="hide"/);
  assert.match(browser, /columns/);
  assert.match(browser, /CatalogCards records={displayRecords} columns={state.columns} showImages=\{state\.images !== "hide"\} showResultPosition/);
  assert.match(browser, /resultPositionOffset/);
  assert.match(browser, /Score \(licensed data only\)/);
  assert.match(browser, /catalog-pagination/);
  assert.match(browser, /className="filter-chip" aria-label=\{`Remove search filter: \$\{state\.q\}`\}/);
  assert.match(browser, /className="filter-chip" aria-label=\{`Remove platform filter: \$\{option\.label\}`\}/);
  assert.match(browser, /className="filter-chip" aria-label=\{`Remove genre filter: \$\{option\.label\}`\}/);
  assert.match(browser, /className="filter-chip" aria-label=\{`Remove year filter: \$\{yearFrom \|\| "Any"\}–\$\{yearTo \|\| "Any"\}`\}/);
  assert.match(browser, /className="filter-chip" aria-label=\{`Remove developer filter: \$\{developerLabel\}`\}/);
  assert.match(browser, /className="filter-chip" aria-label=\{`Remove publisher filter: \$\{publisherLabel\}`\}/);
  assert.match(cards, /Current result position/);
  assert.match(cards, /not a quality ranking/);
  assert.match(cards, /game-card-title-link/);
  assert.match(cards, /data-platform-overflow/);
  assert.match(cards, /data-genre-overflow/);
  assert.match(cards, /<ul className="game-card-topline-platforms"/);
  assert.doesNotMatch(taxonomyHub, /showResultPosition/);
  assert.match(browser, /getCatalogPaginationItems/);
  assert.match(browser, /pagination-ellipsis/);
  assert.match(page, /initialRecords=/);
  assert.match(page, /map\(toCatalogCardRecord\)/);
  assert.match(page, /catalogIndexDigest=/);
  assert.match(page, /catalogIndexUrl=/);
  assert.match(browser, /fetch\(catalogIndexUrl, \{ signal: controller\.signal \}\)/);
  assert.match(browser, /indexRequestRef\.current = null;[\s\S]*indexStatusRef\.current = "error";[\s\S]*setIndexStatus\("error"\)/);
  assert.match(browser, /indexStatusRef\.current === "error" && !force/);
  assert.match(browser, /loadCatalogIndex\(true\)/);
  assert.match(browser, /catalogQueryParamGroups/);
  assert.match(browser, /changedFields/);
  assert.match(browser, /catalog-index-status/);
  assert.match(browser, /searchStateFromUrl\(catalogRecords, new URLSearchParams\(window\.location\.search\)\)/);
  assert.match(browser, /Retry the full catalog/);
  assert.match(browser, /hasCatalogQuery/);
  assert.match(browser, /hasCatalogFilterQuery/);
  assert.match(browser, /Pending filters/);
  assert.match(browser, /IntersectionObserver/);
  assert.match(browser, /rootMargin: "800px 0px"/);
  assert.match(browser, /data-catalog-index-status=\{indexStatus\}/);
  assert.match(browser, /Browse or use filters to load the full catalog/);
  assert.match(browser, /Filter changes will apply when it is ready/);
  assert.match(browser, /Retry full catalog/);
  assert.match(browser, /syncPendingState/);
  assert.match(catalogIndex, /Browse every game\./);
  assert.match(catalogIndex, /No-JavaScript catalog/);
  assert.match(staticExportValidator, /const maximumHomePayloadBytes = 400 \* 1024/);
  assert.doesNotMatch(page, /Curated by humans|Thoughtful recommendations|reviewed picks/);
});

test("visual shell protects focus, contrast, and reduced-motion behavior", () => {
  assert.match(styles, /--faint:\s*#718194/);
  assert.match(styles, /\.skip-link\s*\{/);
  assert.match(styles, /prefers-reduced-motion:\s*reduce/);
  assert.match(styles, /wordmark-orbit/);
  assert.match(styles, /@keyframes wordmark-orbit-spin/);
  assert.match(styles, /overflow-x:\s*clip/);
  assert.match(styles, /game-box\{transition:none/);
  assert.match(styles, /game-grid--columns-1/);
  assert.match(styles, /layout-control/);
  assert.match(styles, /@media \(max-width:800px\)[\s\S]*game-grid\{grid-template-columns:1fr\}/);
  assert.match(styles, /layout-options\{display:flex;gap:5px\}/);
  assert.match(styles, /layout-mobile-note/);
  assert.match(styles, /layout-control:not\(.layout-control--images\)/);
  assert.match(styles, /game-grid--columns-1 \.game-card--no-image \.game-card-body/);
  assert.match(styles, /browser-panel-count/);
  assert.match(styles, /grid-template-columns: minmax\(0, 1fr\) minmax\(170px, \.28fr\)/);
  assert.match(styles, /\.browser-check\s*\{[\s\S]*min-height:\s*44px/);
  assert.match(styles, /catalog-index-status/);
  assert.match(styles, /browser-check-list/);
  assert.match(styles, /game-card-title-link::before/);
  assert.match(styles, /\.tag-list a/);
  assert.match(styles, /forced-colors: active[\s\S]*layout-option--active/);
  assert.match(styles, /game-card-credits>span/);
  assert.doesNotMatch(styles, /\.platform-card:hover\s*\{[^}]*transform/);
});

test("game detail pages expose static params, a skip link, and explicit editorial evidence", () => {
  assert.match(gamePage, /dynamicParams = false/);
  assert.match(gamePage, /generateStaticParams/);
  assert.match(gamePage, /className="skip-link" href="#main-content"/);
  assert.match(gamePage, /Original editorial/);
  assert.match(gamePage, /Catalog method/);
  assert.match(gamePage, /isCatalogMethodEntry/);
  assert.match(gamePage, /PlatformGlyph/);
  assert.match(gamePage, /game-status-row/);
  assert.match(gamePage, /getPlatformDisplayLabel/);
  assert.match(browser, /platformDisplayLabels/);
  assert.match(gamePage, /Official &amp; external resources/);
  assert.match(gamePage, /DSiWare · Digital/);
  assert.match(gamePage, /First documented release/);
});

test("game pages retain governed package views and a visible reference fallback", () => {
  assert.match(gamePage, /GameBoxViewer key=\{game\.slug\} presentation=\{packagePresentation\}/);
  assert.match(gamePage, /site\.assetPath\(boxAsset\.path\.replace/);
  assert.match(gamePage, /Catalog method/);
  assert.match(boxViewer, /GameAtlas reference case/);
  assert.match(boxViewer, /data-game-box-stage/);
  assert.match(boxViewer, /aria-live="polite"/);
  assert.match(boxViewer, /requestFullscreen/);
  assert.match(styles, /game-box-viewer--fallback-fullscreen/);
  assert.match(styles, /forced-colors:active/);
});

test("package UI consumes profile geometry and preserves card-safe thumbnail art", () => {
  assert.match(gamePage, /createPackagePresentation/);
  assert.match(gamePage, /getGameBoxFront/);
  assert.match(boxViewer, /data-package-profile/);
  assert.match(boxViewer, /viewer\.restAngle/);
  assert.match(boxViewer, /presentation\.formatKind === "physical"/);
  assert.match(boxViewer, /onError=\{\(\) => setFailedSource/);
  assert.match(boxViewer, /loading="eager" decoding="async" fetchPriority="high"/);
  assert.match(boxViewer, /loading="lazy" decoding="async" fetchPriority="low"/);
  assert.match(boxViewer, /role="img" aria-label=\{`GameAtlas reference front/);
  assert.match(cards, /PackageThumbnail thumbnail=\{record\.packageThumbnail\}/);
  assert.match(packageThumbnail, /data-package-thumbnail="true"/);
  assert.match(packageThumbnail, /thumbnail\.kind === "physical"/);
  assert.match(packageThumbnail, /loading="lazy" decoding="async"/);
  assert.match(styles, /package-thumbnail__spine/);
  assert.match(styles, /rotateY\(-23deg\)/);
  assert.doesNotMatch(styles, /will-change:\s*transform/);
});
